import React from 'react'
import Image from 'next/image';
import Head from 'next/head';
import Link from "next/link";
import { Inter } from 'next/font/google'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillLinkedin, AiFillGithub, AiFillMail, AiFillProfile } from 'react-icons/ai'
import { MdExpandMore } from "react-icons/md"
import guycoding from '../public/guy-coding.png'
import { useState } from 'react';

import Portfolio from './Portfolio';
import Skills from './Skills';
import Footer from './Footer';

const HomePage = () => {

    return (
        <>
            <div id='home' className='h-screen w-full text-center pt-24 dark:bg-gray-900 ease-in duration-300'>

                <Head>
                    <title>Austin Varghese Portfolio</title>
                    <meta name="decription" content="Generated by create-next-app@latest"></meta>
                    <link rel='icon' href="/favicon.ico"></link>
                </Head>

                <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 duration-300 ease-in'>

                    <section className='md:min-h-full flex flex-col justify-between'>

                        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-72 h-72 lg:w-80 lg:h-80 mt-10 overflow-hidden hidden md:block'>
                            <Image src={guycoding} fill style={{ objectFit: "cover" }} alt='guy coding'></Image>
                        </div>

                        {/* <div className='relative mx-auto bg-gradient-to-b from-indigo-500 rounded-full w-80 h-80 mt-10 overflow-hidden md:h-96 md:w-96'>
                        <Image src={guycoding} fill style={{ objectFit: "cover" }}></Image>
                    </div> */}

                        <div className='text-center p-10'>
                            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Austin Varghese</h2>
                            <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-100'>Software Developer</h3>
                            <p className='text-md py-3 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-300'>I am a Software Engineering Graduate from the University of Guelph with a minor in Business. I have a passion for designing and developing code. This includes experience with technologies such as
                                React, Node.js, SQL, Unity, AWS, Azure, GCP and more.
                            </p>
                        </div>
                        <div className='text-5xl flex justify-center gap-16 pb-8 text-gray-600 md:hidden'>
                            <a href='https://www.linkedin.com/in/austin-fv/' target='_blank' className='hover:scale-105'><AiFillLinkedin /></a>
                            <a href='https://github.com/Austin-FV' target='_blank' className='hover:scale-105'><AiFillGithub /></a>
                            <a href='mailto:austinfv01@gmail.com' className='hover:scale-105'><AiFillMail /></a>
                        </div>

                        <div className='flex justify-center'>

                            <Link href='/#skills' scroll={false} >
                                <div className='group flex items-center justify-center bg-teal-600 text-white py-3 px-5 font-bold uppercase rounded-md tracking-wider'>
                                    learn more
                                    <span className='-rotate-90 duration-100 ease-in group-hover:rotate-0'>
                                        <MdExpandMore size={25}></MdExpandMore>
                                    </span>
                                </div>
                            </Link>
                        </div>

                    </section>

                    <Skills />

                    <Portfolio />

                    <Footer />

                </main>

            </div>
        </>
    )
}

export default HomePage