import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        {/* <title>Austin Varghese Portfolio</title>
        <meta name="decription" content="Generated by create-next-app@latest"></meta>
        <link rel='icon' href="/favicon.ico"></link> */}
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
