import Image from 'next/image';
import Head from 'next/head';
import { Inter } from 'next/font/google'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub, AiFillMail, AiFillProfile} from 'react-icons/ai'
import guycoding from '../public/guy-coding.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"
import { useState } from 'react';
import React from 'react';
// import { Document, Page } from 'react-pdf';
// import resume from "../public/2023-04-30-AustinVargheseResume.pdf"
// import {pdfjs, Document, Page} from 'react-pdf'

// pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.js`


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <div className={inter.className} > 
        <Head>
          <title>Austin Varghese Portfolio</title>
          <meta name="decription" content="Generated by create-next-app@latest"></meta>
          <link rel='icon' href="/favicon.ico"></link>
        </Head>

        <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
          <section className='min-h-screen'>
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='font-bold font-burtons text-xl'>AFV</h1>
              <ul className='flex items-center'>
                <li>
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}
                  className='cursor-pointer text-2xl dark:text-white'/>
                  </li>
                <li>
                  <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" 
                  href='/2023-04-30-AustinVargheseResume.pdf' target='_blank'>Resume</a></li>
              </ul>
            </nav>

            <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Austin Varghese</h2>
              <h3 className='text-2xl py-2 md:text-3xl'>Software Developer</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto'>I am a Software Engineering Graduate from the University of Guelph. I have plenty of experience designing
                and developing code that is up to industry standards. This includes experience with technologies such as 
                React, Node.js, SQL, Unity, AWS, Azure, GCP and more. 
              </p>
            </div>
            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <a href='https://www.linkedin.com/in/austin-fv/' target='_blank'><AiFillLinkedin/></a>
              <a href='https://github.com/Austin-FV' target='_blank'><AiFillGithub/></a>
              <a href='mailto:austin.varghese7@gmail.com' target='_blank'><AiFillMail/></a>
            </div>

            <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
              <Image src={guycoding} fill style={{objectFit:"cover"}}></Image>
            </div>
          </section>
          <section>
          <div className='pt-5'>
              <h3 className='text-3xl py-1'>Experience</h3>
              <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200'>Here are some of the   
              <span className='text-teal-500'> technologies </span>I have worked with!</p>
            </div>
          </section>
          <section>
            <div className='pt-5'>
              <h3 className='text-3xl py-1'>Services I offer</h3>
              <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200'>some more  
              <span className='text-teal-500'> extra </span>text here</p>
            </div>

            <div className='lg:flex gap-10'>
              <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
                <div className='flex justify-center'>
                  <Image src={design} width={100} height={100}/>
                </div>
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
                <p className='py-2'>
                  Creating elegant design suited for your needs and design theory.
                </p>
                <h4 className='py-4 text-teal-600'>Design Tools Used</h4>
                <p className='text-gray-800 py-1'>Figma</p>
              </div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                <div className='flex justify-center'>
                  <Image src={code} width={100} height={100}/>
                </div>
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
                <p className='py-2'>
                  Creating elegant design suited for your needs and design theory.
                </p>
                <h4 className='py-4 text-teal-600'>Design Tools Used</h4>
                <p className='text-gray-800 py-1'>Figma</p>
              </div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                <div className='flex justify-center'>
                  <Image src={consulting} width={100} height={100}/>
                </div>
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
                <p className='py-2'>
                  Creating elegant design suited for your needs and design theory.
                </p>
                <h4 className='py-4 text-teal-600'>Design Tools Used</h4>
                <p className='text-gray-800 py-1'>Figma</p>
              </div>
            </div>

          </section>

          <section>
            <div>

              <h3 className='text-3xl py-1'>Portfolio</h3>
              <p className='text-md py-5 leading-8 text-gray-800'>some more  
              <span className='text-teal-500'> extra </span>text here</p>

            </div>

            <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
              <div className='basis-1/3 flex-1 flex justify-center'>
                <Image src={web1} className='rounded-lg object-cover' width={'500'} height={'500'} />
              </div>
              <div className='basis-1/3 flex-1 flex justify-center'>
                <Image src={web2} className='rounded-lg object-cover' width={'500'} height={'500'} />
              </div>
              <div className='basis-1/3 flex-1 flex justify-center'>
                <Image src={web3} className='rounded-lg object-cover' width={'500'} height={'500'} />
              </div>
              <div className='basis-1/3 flex-1 flex justify-center '>
                <Image src={web4} className='rounded-lg object-cover' width={'500'} height={'500'} />
              </div>
              <div className='basis-1/3 flex-1 flex justify-center'>
                <Image src={web5} className='rounded-lg object-cover' width={'500'} height={'500'} />
              </div>
              <div className='basis-1/3 flex-1 flex justify-center'>
                <Image src={web6} className='rounded-lg object-cover' width={'500'} height={'500'} />
              </div>
            </div>
          </section>

          <section>
            <div className='pt-5'>
              <h3 className='text-3xl py-1'>Contact Me</h3>
              <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200'>some more  
              <span className='text-teal-500'> extra </span>text here</p>
            </div>
          </section>
        </main>
      </div>
    </div>
  )
}
